package com.company.store.eventsys.events;

public enum EventIdentifier {
    CHANGE_VIEW, CHANGE_ADDRESS_ACCEPTED, CANCEL_SUCCESS, RETURN_ACCEPTED, USERSCAN, CONFIRM, BUTTON_REFERENCE,
    PURCHASE_COMPLETED, CHANGE_ADDRESS_REFUSED, CANCEL_REFUSED, RETURN_REFUSED, TEST, REGISTRATION_PROCEDURE,
    REGISTRATION_ACCEPTED, REGISTRATION_REFUSED, LOGIN_ACCEPTED, LOGIN_REFUSED, LOGOUT_ACCEPTED, LOGOUT_REFUSED,
    REGISTER_REQUEST, LOGIN_REQUEST, LOGOUT_REQUEST
}
