package com.company.store.eventsys.events;

public enum EventIdentifier {
    CHANGE_VIEW, LOG_OUT, REGISTER, LOGIN, CHANGE_ADDRESS, CANCEL, RETURN, USERSCAN, CONFIRM, BUTTON_REFERENCE,
    PURCHASE_COMPLETED, CHANGE_ADDRESS_REFUSED, CANCEL_REFUSED, RETURN_REFUSED
}
