package com.company.store.eventsys.events;

public enum EventIdentifier {
    CHANGE_ADDRESS_ACCEPTED, CANCEL_SUCCESS, RETURN_ACCEPTED,
    PURCHASE_COMPLETED, CHANGE_ADDRESS_REFUSED, CANCEL_REFUSED, RETURN_REFUSED, TEST,
    REGISTER_REQUEST, LOGIN_REQUEST, LOGOUT_REQUEST, OPERATION_COMPLETED;
}
