package com.company.store.events.requests;

public enum RequestIdentifier {
    LOGIN_REQUEST, REGISTER_REQUEST, LOGOUT_REQUEST, CANCEL_REQUEST, CHANGE_ADDRESS_REQUEST,
    RETURN_REQUEST, PURCHASE_REQUEST, ADD_TO_CART_REQUEST;
}
