package com.company.constants;

public enum ButtonIdentifier {
    BACK, LOG_OUT, CATALOG, CART, HISTORY, LOGIN, REGISTER, HOME, INSERTEMAIL, INSERTPASSWORD, CONFIRM_REGISTRATION, CONFIRM_LOGIN, SHIPMENT
}
